backup_before_operations: true
batch_size: 100
exiftool_path: null
gui_remember_settings: true
gui_settings:
  window_position:
  - 599
  - 131
  window_size:
  - 1000
  - 700
gui_theme: light
gui_window_size:
- 1200
- 800
log_level: INFO
max_file_size_mb: 500
max_workers: 4
memory_limit_mb: 1024
progress_bar: true
quiet: false
supported_formats:
- .jpg
- .jpeg
- .png
- .tif
- .tiff
- .webp
- .bmp
temp_dir: null
verbose: false
